A = int(input())
B = int(input())
C = int(input())
N = str(A*B*C)
print(N.count('0'))
print(N.count('1'))
print(N.count('2'))
print(N.count('3'))
print(N.count('4'))
print(N.count('5'))
print(N.count('6'))
print(N.count('7'))
print(N.count('8'))
print(N.count('9'))